FROM --platform=linux/amd64 ubuntu:20.04

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y automake pkg-config libtool build-essential

ADD . /repo
WORKDIR /repo
RUN autoreconf -if
RUN ./configure
RUN make -j8
ENV LD_LIBRARY_PATH=/repo/libcpuid/.libs
